spring:
  profiles:
    active: local

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: test-topic
    producer: 
      bootstrap-servers: localhost:9092, localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: localhost:9092, localhost:9093
        
---
spring:
  profiles: dev
  kafka:
    producer: 
      bootstrap-servers: dev1:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
---

spring:
  profiles: prod
  kafka:
    producer: 
      bootstrap-servers: prod1:9092,
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer